server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/

spring:
  application:
    name: service_feign
## 开启feign自带的hystrix断路器
feign:
  hystrix:
    enabled: true